// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromotionPiece } from "./PromotionPiece";

/**
 * All possible messages a client can send to the server.
 */
export type ClientMessage = { "kind": "Authenticate", 
/**
 * Secret token that identifies this player.
 */
token: string, 
/**
 * Display name for this player.
 */
name: string, } | { "kind": "UpdateName", 
/**
 * New player name (1-25 characters).
 */
name: string, } | { "kind": "Ready", 
/**
 * Whether the player is ready (true) or not ready (false).
 */
ready: boolean, } | { "kind": "MakeMove", 
/**
 * The starting coordinate of the piece being moved.
 */
from: Coordinate, 
/**
 * The destination coordinate.
 */
to: Coordinate, 
/**
 * The piece to promote to, if this is a pawn promotion move.
 * Valid values: "Q" | "R" | "B" | "N"
 */
promotion: PromotionPiece | null, } | { "kind": "RequestSync" } | { "kind": "OfferDraw" } | { "kind": "AcceptDraw" } | { "kind": "DeclineDraw" } | { "kind": "Resign" } | { "kind": "Heartbeat" };
