// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The reason a game ended.
 *
 * These are machine-readable codes that the frontend should translate
 * into human-readable messages (allowing for i18n and customization).
 */
export type GameEndReason = "checkmate" | "stalemate" | "resignation" | "draw_agreement" | "threefold_repetition" | "fifty_move_rule" | "insufficient_material" | "timeout" | "abandoned";
