// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result of a completed game.
 */
export type GameResult = "WhiteWins" | "BlackWins" | "Draw";
