// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reasons why a move might be rejected.
 */
export type MoveRejectionReason = "InvalidNotation" | "IllegalMove" | "NotYourTurn" | "GameOver";
