// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A player's connection status.
 */
export type PlayerConnectionStatus = "Connected" | "Disconnected" | "Reconnecting";
