// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a player.
 */
export type PlayerInfo = { 
/**
 * The player's display name.
 */
name: string, 
/**
 * Whether this player is currently connected.
 */
connected: boolean, };
