// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthFailureReason } from "./AuthFailureReason";
import type { MoveRejectionReason } from "./MoveRejectionReason";
import type { PlayerInfo } from "./PlayerInfo";

/**
 * Events sent only to specific players.
 *
 * These contain sensitive information or player-specific
 * feedback that spectators should not see.
 */
export type PrivateEvent = { "kind": "LobbyJoined", 
/**
 * Player slot number (1 or 2).
 * Use this to identify yourself in subsequent events like NameChanged.
 */
slot: number, 
/**
 * Player 1 info (if present).
 */
player1: PlayerInfo | null, 
/**
 * Player 2 info (if present).
 */
player2: PlayerInfo | null, 
/**
 * Ready status for player 1.
 */
player1_ready: boolean, 
/**
 * Ready status for player 2.
 */
player2_ready: boolean, } | { "kind": "ColorsAssigned", 
/**
 * Whether this client is playing as White or Black.
 */
player: Color, } | { "kind": "AuthenticationFailed", 
/**
 * The reason authentication was rejected.
 */
reason: AuthFailureReason, } | { "kind": "MoveRejected", 
/**
 * The reason the move was rejected.
 */
reason: MoveRejectionReason, } | { "kind": "HeartbeatAck" } | { "kind": "StateSync", 
/**
 * The current game/board state.
 */
game_state: Game, 
/**
 * Which player's turn it is.
 */
current_turn: Color, 
/**
 * Information about the white player.
 */
white_player: PlayerInfo, 
/**
 * Information about the black player.
 */
black_player: PlayerInfo, 
/**
 * Which player offered a draw, if any (pending draw offer).
 */
draw_offered_by: Color | null, 
/**
 * Number of moves made so far.
 */
move_count: number, 
/**
 * The color this player is playing as.
 */
your_color: Color, 
/**
 * Game result if the game has ended, null if still in progress.
 */
game_result: GameResult | null, 
/**
 * Reason the game ended, if it has ended.
 */
game_end_reason: GameEndReason | null, } | { "kind": "DrawOffered" } | { "kind": "DrawDeclined" };
