// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The piece a pawn can be promoted to.
 *
 * This enum uses single-letter notation (standard in chess) that maps to TypeScript union type.
 */
export type PromotionPiece = "Q" | "R" | "B" | "N";
