// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameEndReason } from "./GameEndReason";
import type { GameResult } from "./GameResult";
import type { PlayerConnectionStatus } from "./PlayerConnectionStatus";
import type { PlayerInfo } from "./PlayerInfo";
import type { PromotionPiece } from "./PromotionPiece";

/**
 * Events visible to all players and spectators.
 *
 * These events are broadcast to everyone watching the game.
 * Spectators only receive public events.
 */
export type PublicEvent = { "kind": "GameStarted", 
/**
 * The initial game state (starting position).
 */
game_state: Game, 
/**
 * Information about the white player.
 */
white_player: PlayerInfo, 
/**
 * Information about the black player.
 */
black_player: PlayerInfo, } | { "kind": "MoveMade", 
/**
 * The player who made the move.
 */
author: Color, 
/**
 * The starting coordinate of the piece that was moved.
 */
from: Coordinate, 
/**
 * The destination coordinate.
 */
to: Coordinate, 
/**
 * The piece the pawn was promoted to, if applicable.
 */
promotion: PromotionPiece | null, 
/**
 * The new game state after the move.
 */
new_state: Game, 
/**
 * Whether the move puts the opponent in check.
 */
is_check: boolean, 
/**
 * Whether the move results in checkmate.
 */
is_checkmate: boolean, } | { "kind": "GameOver", 
/**
 * The final result of the game.
 */
result: GameResult, 
/**
 * The reason the game ended (machine-readable, frontend should provide human-readable message).
 */
reason: GameEndReason, } | { "kind": "PlayerStatusChanged", 
/**
 * Which player's status changed.
 */
player: Color, 
/**
 * The new connection status.
 */
status: PlayerConnectionStatus, } | { "kind": "NameChanged", 
/**
 * Which player's name changed (White or Black - assigned when game starts).
 */
player: Color, 
/**
 * Player slot (1 or 2) - use this to identify if it's you or opponent.
 */
slot: number, 
/**
 * The new display name.
 */
name: string, } | { "kind": "PlayerReady", 
/**
 * Which player's status changed (White or Black - assigned when game starts).
 */
player: Color, 
/**
 * Player slot (1 or 2) - use this to identify if it's you or opponent.
 */
slot: number, 
/**
 * Whether the player is now ready (true) or not ready (false).
 */
ready: boolean, } | { "kind": "Countdown", 
/**
 * Seconds remaining (5, 4, 3, 2, or 1).
 */
seconds: number, } | { "kind": "GameStarting" } | { "kind": "PlayerLeftLobby", 
/**
 * Player slot (1 or 2) that left.
 */
slot: number, } | { "kind": "DrawOffered", player: Color, } | { "kind": "DrawDeclined", player: Color, };
