// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrivateEvent } from "./PrivateEvent";
import type { PublicEvent } from "./PublicEvent";

/**
 * A server message containing either a public or private event.
 *
 * This is the top-level message type sent from server to clients.
 * Players receive both public and private events, while spectators
 * only receive public events.
 */
export type ServerMessage = { "visibility": "Public", "event": PublicEvent } | { "visibility": "Private", "event": PrivateEvent };
