#!/usr/bin/env bash

set -e

export CARGO_HOME=/vercel/.cargo
export RUSTUP_HOME=/vercel/.rustup
source "$CARGO_HOME/env"

echo "Building chers..."
cd ../..
wasm-pack build --release --target web --out-dir chers_web/generated/chers chers
cargo test -p chers

echo "Building chers_web..."
cd chers_web
bun run build
