#!/usr/bin/env bash

set -e

export CARGO_HOME=/vercel/.cargo
export RUSTUP_HOME=/vercel/.rustup
source "$CARGO_HOME/env"

echo "Building chers..."
cd ../chers
cargo metadata
cargo test
wasm-pack build --release --target web

echo "Building chers_web..."
cd ../chers_web
bun run build
