#!/usr/bin/env bash

set -e

echo "Installing Rust..."
amazon-linux-extras install rust1

echo "Installing wasm-pack..."
curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -y

echo "Installing NPM Dependencies..."
bun install
